### ISSUE TITLE
difference

### ISSUE THREAD

**Issue by mbfakourii** [amiralitaheri/jdate_dart#3]
سلام کتابخونه عالیه هست اگر ممکنه روی 
difference 
بیشتر کار کنید مثلا بگه دو ساعت از پست گذشته یا دو روز گذشته یا ۱۰ ماه یا ۱۰ سال و... اگر تابعی برای این موضوع بود خیلی عالی بود البته 
difference 
تا اینجا چیز خوبیه ولی اگر این پارامتر بهش اضافه میکردین عالی بود که خودش تشخیص بده اگر ۲۳ ساعت شد ۲۴ ساعت دیگه ننویسه ساعت بگه یک روز گذشته

@amiralitaheri

**Comment by amiralitaheri** [comment]
سلام ممنون بابت نظرتون
با توجه به پیشنهاد آقای
@SamadiPour 
سعی کردیم ساختار کلی شبیه کتابخونه رسمی
dart
باشه

و خوب تابع رسمی کتابخونه
[DateTime](https://api.dart.dev/stable/2.10.3/dart-core/DateTime-class.html)
هم برای اختلاف یک
ِ[Duration](https://api.dart.dev/stable/2.10.3/dart-core/Duration-class.html)
برمی گردونه

و اگر هم قرار باشه پیشنهاد شما رو پیاده سازی کنیم، هر ماه رو باید چند روز درنظر بگیریم؟
29،30,31
هر سال رو باید چند روز در نظر بگیریم؟

به نظرم بهترین حالت اینه که خودتون یه اکستنشن متد مانند زیر درنظر بگیرید و با توجه به نیازتون شخصی سازیش کنید. چون فکر نکنم همه بتونند روی یک استاندارد واحد توافق کنن
```dart
String _printDuration(Duration duration) {
  String twoDigits(int n) => n.toString().padLeft(2, '0');
  var twoDigitMonth = twoDigits((duration.inDays/30).floor());
  var twoDigitDay = twoDigits(duration.inDays.remainder(30));
  var twoDigitHour = twoDigits(duration.inHours.remainder(24));
  var twoDigitMinutes = twoDigits(duration.inMinutes.remainder(60));
  var twoDigitSeconds = twoDigits(duration.inSeconds.remainder(60));
  return '$twoDigitMonth/$twoDigitDay $twoDigitHour:$twoDigitMinutes:$twoDigitSeconds';
}
```
 بازم در آینده اگه کتابخونه ی رسمی سر استانداردی به توافق برسه و همچین قابلیتی رو اضافه کنه حتما این قابلیت رو ما هم اضافه میکنیم

بازم خوشحال میشم اگه نظری داشتید بگید

**Comment by SamadiPour** [comment]
امیرعلی من تو این مورد تاحدودی موافقم که بذاریم
درواقع تابع درخواستی چیزی مثل diffForHumans تو لایبری Carbon لاراول هستش
به نظرم اگر با همین اسم بهش اضافه کنیم خوب میشه.
اگر موافقی که دوباره issue رو باز کن و روش فکر و کار کنیم.

**Comment by SamadiPour** [comment]
پکیج مشابه برای تقویم میلادی:
https://pub.dev/packages/timeago

**Comment by SamadiPour** [comment]
جالبه!
مثل این که فارسی هم داره
پس به نظرم لازم نیست ما دوباره پیاده سازی کنیم

http://andresaraujo.github.io/timeago.dart/#

**Comment by amiralitaheri** [comment]
خب من هم 
https://carbon.nesbot.com/docs/#api-humandiff
رو نگاه کردم و هم 
https://pub.dev/packages/timeago

ولی در کل خیلی چیزها رو باید توافق کنی، فرمت نمایشش چه جوری باشه یا مثلا شاید مثل تلگرام از یه زمانی به بعد بخوای یه پیام دیگه رو نشون بده مثل 
last seen "a long time ago"

و در کل مثل تبدیل تاریخها نیست، منطق سختی نداره و پیاده سازیش راحته
برای همین برنامه نویس خیلی راحت میتونه موقع پیاده سازی خودش با توجه به منظور و هدف برنامه شخصی سازیش کنه
برای همین مخالفم برای پیاده سازیش

و حتی اگه قرار به پیاده سازی بود به نظرم باید یه
extension
روی
duration
میبود
و نمیدونم چرا این کتابخونه 
https://pub.dev/packages/timeago
اینجوری پیاده سازی کرده

**Comment by mbfakourii** [comment]
https://pub.dev/packages/jiffy
